import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { access, copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";

const production = process.argv[2] === "production";
const pluginId = JSON.parse(await readFile("manifest.json", "utf8")).id;
const builtins = [...builtinModules, ...builtinModules.map((module) => `node:${module}`)];

function developmentPluginDirectory() {
  if (process.env.VAULT_PLUGIN_DIR !== undefined) {
    return process.env.VAULT_PLUGIN_DIR;
  }

  try {
    const vaultDirectory = readFileSync(".dev-vault", "utf8").trim();
    return vaultDirectory
      ? join(vaultDirectory, ".obsidian", "plugins", pluginId)
      : "";
  } catch {
    return "";
  }
}

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function deploy() {
  const outputDirectory = developmentPluginDirectory();
  if (!outputDirectory || !(await exists(dirname(dirname(outputDirectory))))) {
    return;
  }

  await mkdir(outputDirectory, { recursive: true });
  for (const asset of ["main.js", "manifest.json"]) {
    await copyFile(asset, join(outputDirectory, asset));
  }
  await writeFile(join(outputDirectory, ".hotreload"), "");
  console.log(`Deployed to ${outputDirectory}`);
}

const context = await esbuild.context({
  banner: {
    js: "/* Generated by esbuild. Edit the TypeScript sources instead. */",
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    {
      name: "deploy-to-vault",
      setup(build) {
        build.onEnd(async (result) => {
          if (result.errors.length === 0) {
            await deploy();
          }
        });
      },
    },
  ],
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}

